### ISSUE TITLE
bios setting

### ISSUE THREAD

**Issue by ghost** [Pai2Chen/OpenCore-Asus-TUF-B450M-Plus-Gaming#3]
你好！bios需要变更哪些设置阿

**Comment by Dreamail** [comment]
跟一般的安装教程是一样的，
主要是安全启动，
https://blog.xjn819.com/?p=543可以参考一下这教程

**Comment by bobobobo9** [comment]
> 跟一般的安装教程是一样的，
> 主要是安全启动，
> [https://blog.xjn819.com/?p=543可以参考一下这教程](https://blog.xjn819.com/?p=543%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%E8%BF%99%E6%95%99%E7%A8%8B)

**Comment by ghost** [comment]
多谢！
