### ISSUE TITLE
显卡似乎不满载

### ISSUE THREAD

**Issue by ghost** [Pai2Chen/OpenCore-Asus-TUF-B450M-Plus-Gaming#5]
显卡感觉利用率跑不起来 老哥有遇到过吗 删掉whatevergreen也一样

**Comment by Dreamail** [comment]
检查一下驱动有没有打上，另外是什么显卡

**Comment by ghost** [comment]
rx570 搜了下是要独显注入吗

**Comment by ghost** [comment]
geekbench跑分好像是正常的 能到3w

**Comment by Dreamail** [comment]
是用什么软件监测显卡利用率的，AMD平台貌似很多监测都不准

**Comment by ghost** [comment]
sensei 负载是有上去



---原始邮件---
发件人: "Pai2Chen"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 中午12:08
收件人: "Pai2Chen/OpenCore-Asus-TUF-B450M-Plus-Gaming"<OpenCore-Asus-TUF-B450M-Plus-Gaming@noreply.github.com&gt;;
抄送: "bobobobo9"<1412393182@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Pai2Chen/OpenCore-Asus-TUF-B450M-Plus-Gaming] 显卡似乎不满载 (#5)




 
是用什么软件监测显卡利用率的，AMD平台貌似很多监测都不准

**Comment by Dreamail** [comment]
跑分正常应该就没什么问题，至于负载上不去应该是没给负载，正常使用有问题么

**Comment by ghost** [comment]
正常使用没什么问题 不纠结这个了
