### ISSUE TITLE
bui‌‌ldin sound not‌‌‌  working !

### ISSUE THREAD

**Issue by TomPuca** [Pai2Chen/OpenCore-Asus-TUF-B450M-Plus-Gaming#7]
My PC not have buildin sound in PCI. And using my DSDT benchmark is higher

**Comment by Dreamail** [comment]
all of AMD hackintosh machines' buildin mic couldn't work,so I didn't using buildin sounds card,if you need buildin sounds card, you can put AppleALC.kext(mic couldn't work) or VoodooHDA.kext(might cause other problems,but mic could work) in the kexts folder.

**Comment by Dreamail** [comment]
And what dsdt you are using?

**Comment by andreescampos** [comment]
First of all, thnx for your work. About your last comment, why board audio isnt working? VoodooHDA.kext is already in Kext folder

**Comment by TomPuca** [comment]
thanks for your work !
after tesing, 2 problem with my PC:
- buildin Audio not work (i can using another adapter).
- Some USB port not work.
So, i recover to my OC 5.0.8 (everything work well). Maybe i will check it late :)

**Comment by Dreamail** [comment]
the VoodooHDA.kext in the kexts folder was disabled in oc config
i used USBPort.kexts to fix USB problem，but i haven't test every USB port.
if you have another problem，plz continue commenting.if you have better way to fix the problem，plz make a pr.

**Comment by TomPuca** [comment]
Dear !
After using USBMap.kext and USBPort.kext from https://github.com/SandiTT/Hackintosh-3700X-5700-B450M-Catalina-10.15.7.
USB work perfectly :)
Waiting you update to the newest OC (because when i using EFI Folder from the link above, my Network Card stay at un pluged state :( )
